# Generated by Django 2.1.4 on 2018-12-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='untitled', max_length=50)),
                ('testcase_id', models.CharField(default='', max_length=400)),
                ('testcase_vals', models.CharField(default='', max_length=400)),
                ('generated_text', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
